import '../Styles/globals.scss';
import { Navbar, Footer } from "@/components";
import Providers from "./provider";



export const metadata = {
  title: "meta verse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" style={{colorScheme:'dark'}}>
      <body className="dark:bg-gray-900 bg-[#fff] text-slate-800  dark:text-white">
        <Providers>
        <div className="main__container  w-full ">
          <Navbar />

          {children}

          <Footer />
        </div>
        </Providers>
       
      </body>
    </html>
  );
}
